import { useEffect, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { api, type Schedule } from "../../api/client";
import { Button } from "../../components/Button";
const blank = { enabled: true, start_time: "", stop_time: "", backup_before_stop: true, power_off_after_stop: false, wake_time: "" };
export function SchedulePanel({ profileId }: { profileId: string }) {
  const cache = useQueryClient(); const schedules = useQuery({ queryKey: ["schedules"], queryFn: () => api<Schedule[]>("/schedules") }); const [form, setForm] = useState(blank); const existing = schedules.data?.find(x => x.profile_id === profileId);
  useEffect(() => setForm(existing ? { enabled: existing.enabled, start_time: existing.start_time ?? "", stop_time: existing.stop_time ?? "", backup_before_stop: existing.backup_before_stop, power_off_after_stop: existing.power_off_after_stop, wake_time: existing.wake_time ?? "" } : blank), [profileId, existing]);
  const save = useMutation({ mutationFn: () => api<Schedule>(`/schedules/${profileId}`, { method: "PUT", body: JSON.stringify({ profile_id: profileId, ...form, start_time: form.start_time || null, stop_time: form.stop_time || null, wake_time: form.wake_time || null }) }), onSuccess: () => void cache.invalidateQueries({ queryKey: ["schedules"] }) }); const set = (key: keyof typeof form, value: string | boolean) => setForm(x => ({ ...x, [key]: value }));
  return <section className="card" id="schedule"><div className="section-heading"><div><p className="eyebrow">Automation</p><h2>Server schedule</h2></div><span>{existing?.enabled ? "Active" : "Not scheduled"}</span></div><p className="muted-note">Times use this computer’s local time. A scheduled stop flushes Minecraft saves, creates compressed world backups, then stops cleanly.</p><div className="schedule-grid"><label><input type="checkbox" checked={form.enabled} onChange={e => set("enabled", e.target.checked)} /> Enable daily schedule</label><label>Start server<input type="time" value={form.start_time} onChange={e => set("start_time", e.target.value)} /></label><label>Stop server<input type="time" value={form.stop_time} onChange={e => set("stop_time", e.target.value)} /></label><label><input type="checkbox" checked={form.backup_before_stop} onChange={e => set("backup_before_stop", e.target.checked)} /> Save and back up before stopping</label></div><div className="power-schedule"><h3>Computer power (Linux)</h3><label><input type="checkbox" checked={form.power_off_after_stop} onChange={e => set("power_off_after_stop", e.target.checked)} disabled={!form.stop_time} /> Shut down computer after the safe stop</label>{form.power_off_after_stop && <label>Wake computer next day at<input type="time" value={form.wake_time} onChange={e => set("wake_time", e.target.value)} /><small>Requires compatible RTC wake hardware and the installer power helper.</small></label>}</div>{save.error && <p className="error">{save.error.message}</p>}<Button onClick={() => save.mutate()} disabled={save.isPending}>{save.isPending ? "Saving…" : "Save schedule"}</Button></section>;
}
