import { useEffect, useState, type FormEvent } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { api, type ModConfigDocument, type ModConfigsView } from "../../api/client";
import { Button } from "../../components/Button";
import { formatBytes } from "../../lib/format";

export function ModConfigEditor({ profileId, stopped }: { profileId: string; stopped: boolean }) {
  const client = useQueryClient();
  const [selected, setSelected] = useState("");
  const [content, setContent] = useState("");
  const [notice, setNotice] = useState("");
  const files = useQuery({ queryKey: ["mod-configs", profileId], queryFn: () => api<ModConfigsView>(`/profiles/${profileId}/configs`) });
  const document = useQuery({ queryKey: ["mod-config", profileId, selected], queryFn: () => api<ModConfigDocument>(`/profiles/${profileId}/configs/file?path=${encodeURIComponent(selected)}`), enabled: Boolean(selected) });
  useEffect(() => { if (document.data) setContent(document.data.content); }, [document.data]);
  const save = useMutation({
    mutationFn: () => api<ModConfigDocument>(`/profiles/${profileId}/configs/file`, { method: "PUT", body: JSON.stringify({ path: selected, revision: document.data?.revision, content }) }),
    onSuccess: result => { client.setQueryData(["mod-config", profileId, selected], result); setNotice("Configuration saved. Restart the server to apply it."); },
    onError: error => setNotice(error.message),
  });
  function submit(event: FormEvent) { event.preventDefault(); if (document.data) save.mutate(); }
  const entries = files.data?.files ?? [];
  return <div className="mod-config-editor">
    <div>
      <h3>Configuration files</h3>
      <p className="muted-note">Edit text configuration generated by installed mods. Every save keeps a recovery copy.</p>
      <ul className="config-file-list">{entries.map(entry => <li key={entry.path}><button type="button" className={selected === entry.path ? "is-selected" : ""} onClick={() => { setSelected(entry.path); setNotice(""); }}>{entry.path}<small>{formatBytes(entry.size_bytes)}</small></button></li>)}</ul>
      {files.data && !entries.length && <p className="empty-note">No editable files exist in config/ yet. Many mods create them after the first successful start.</p>}
    </div>
    <div>
      <h3>{selected || "Choose a file"}</h3>
      {selected && document.isLoading && <p className="empty-note">Loading configuration…</p>}
      {document.data && <form onSubmit={submit}><textarea aria-label="Configuration content" value={content} onChange={event => setContent(event.target.value)} spellCheck={false} /><div className="settings-actions"><Button disabled={!stopped || save.isPending || content === document.data.content}>{save.isPending ? "Saving…" : "Save configuration"}</Button><Button type="button" className="button--quiet" onClick={() => setContent(document.data?.content ?? "")}>Discard edits</Button></div></form>}
      {!stopped && selected && <p className="muted-note">Stop the server before saving configuration.</p>}
      {notice && <p className={notice.startsWith("Configuration saved") ? "success" : "error"} role="status">{notice}</p>}
    </div>
  </div>;
}
