#Minecraft server properties
#Mon Jul 17 09:00:00 EDT 2026
enable-jmx-monitoring=false
rcon.port=25575
level-seed=
gamemode=survival
generator-settings={}
enforce-secure-profile=true
level-name=world
motd=\u00A7aA Minecraft Server
query.port=25565
pvp=false
rcon.password=
max-players=20
